#! /bin/bash

# this script runs only on the very first boot
# will be visible at
# curl http://169.254.169.254/latest/user-data

# will run from /var/lib/cloud/instances/instance-id/
# output will go to /var/log/cloud-init-output.log


exec > /tmp/aboot.out 2>&1

set -x
date

if [ "x$ABOOT_HOSTNAME" != "x" ]
then
    echo "$ABOOT_HOSTNAME" > /etc/hostname
    hostname $ABOOT_HOSTNAME
fi

adduser --disabled-password --gecos "$ABOOT_GECOS" $ABOOT_USER

addgroup sudo2
adduser $ABOOT_USER sudo2
echo '%sudo2 ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/99-sudo2

s=/home/$ABOOT_USER/.ssh
mkdir -m 700 -p $s

cp /home/ubuntu/.ssh/authorized_keys $s/

chown -R $ABOOT_USER:$ABOOT_USER $s
chmod 700 $s


export DEBIAN_FRONTEND=noninteractive

apt-get update -y
apt-get upgrade -y

date

apt-get install -y \
	emacs-nox \
	git \
	build-essential \
	python3-pip \
	pwgen \
	apache2 \
	libapache2-mod-php \
	apt-file \
	pkg-config \
	libreadline-dev \
	php-xdebug \
	mlocate

a2enmod php7.3
a2enmod headers
a2enmod rewrite
a2enmod ssl

echo "ServerName localhost" >> /etc/apache2/apache2.conf

if [ "x$ABOOT_EBS_UUID" != "x" ]
then
    mkdir -p /a
    chown $ABOOT_USER /a
    echo "UUID=\"${ABOOT_EBS_UUID}\" /a xfs defaults,nofail 0 2" >> /etc/fstab
    (mount ${mdir} ; chown $GBOOT_USER ${mdir}) &
fi

